language: python
env:
    - TOXENV=django16
    - TOXENV=django15
    - TOXENV=django16
    - TOXENV=django17
    - TOXENV=django18
    - TOXENV=django19
    - TOXENV=coverage
install:
    - pip install tox
script:
    - tox
